[maze_colors]
cell   = "#FFFFFF"
road   = "#DFDFDF"
wall   = "#1C1C1C"
blok   = "#FF7F4D"
shadow = "#B25936"
visited = "#828282"
connected = "#FCAC8C"
path = "#25CD81"

entry  = "#B25936"
exit   = "#1C1C1C"
