[maze_colors]
cell   = "#FFFFFF"
road   = "#DFDFDF"
wall   = "#1C1C1C"
blok   = "#FF5C4A"
shadow = "#CF4D3E"
visited = "#828282"
connected = "#F78F83"
path = "#25CD81"

entry  = "#FF5C4A"
exit   = "#1C1C1C"
